name: Page Build and Deploy

on:
  push:
    branches:
      - main  # 触发条件，当 main 分支有 push 事件时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # 运行环境

    steps:
    - name: Checkout Source
      uses: actions/checkout@v2  # 检出代码

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # 选择 Node.js 版本

    - name: Install Dependencies
      run: |
        npm install  # 安装依赖
        python -m venv .venv
        source .venv/bin/activate

    - name: Build Pages
      run: npm run docs:build

    - name: Create Sitemap
      run: python sitemap.py

    - name: Set Git information  # 设置git信息
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]" 

    - name: Switch baranch  # 切换分支
      run: |
        git checkout -b pages

    - name: Clear barauch files # 清除当前分支内容
      run: git rm -rf .

    - name: Copy files # 复制生成的静态文件到pages分支
      run: cp -r ./dist/* .

    - name: Clear unuseful files # 清除无用文件
      run: |
        rm -rf ./public
        rm -rf ./node_modules
        rm -rf ./.venv
    
    - name: Deploy to pages Branch
      run: |
        # 添加所有文件到 git
        git add .

        # 提交更改
        git commit -m "Update pages branch with latest build"

        # 推送到远程 HTML 分支
        git push origin pages --force